### PR TITLE
Fix conversion from rpm space to mm/s space

### LINKED ISSUE #120: Pulley tooth count not increasing max speed
Pulley circumference scales linearly with tooth count, so doubling teeth doubles linear speed for a given RPM, and halves available torque. The expected behavior is that increasing pulley tooth count should increase the required torque and the maximum speed (presuming a motor has the available torque). 

The behavior the site currently has is that increasing pulley tooth count increases the required torque, but does not shift the motor torque curves as expected. The images below demonstrate this.

With 20 teeth the max speed for this motor is around 760mm/s:
Image
Increasing the tooth count by a factor of 10 to 200 teeth, the required torque gets shifted upward,  but the motor curve does not get stretched to the right by a factor of 10. The motor should be making 10x the linear distance per revolution, and thus gain a 10x increase in speed at the cost of 10x increase in required torque. However, the max speed actually decreases.
Image

This appears to indicate that motor torque is plotted in RPM space, not linear speed space. 

Solution: correctly account for the pulley diameter in converting from RPM space to linear speed space.

### PR DESCRIPTION
**Pull request by Gareth42**
fixes #120

I'm no dev, so this was done with the help of AI. I tested the changes and it appears to be working as expected.

### CODE REVIEW

File: src/components/graph.tsx [hunk 1]
```diff
@@ -16,6 +16,8 @@ import { CartesianGrid, Line, LineChart, ReferenceLine, XAxis, YAxis } from 'rec
 
 const STEP_SIZE = 20;
 const DEFAULT_MAX_VELOCITY = 2000;
+const pitchMm = 2; // GT2 belt, 2mm pitch
```
Comment (TheDevMinerTV) [inline src/components/graph.tsx]: Can you add a setting in the gantry settings to choose between the different belt pitches?

**Review by TheDevMinerTV — CHANGES_REQUESTED** [review]

File: src/components/graph.tsx (hunk 1 above)
Comment (TheDevMinerTV) [reply src/components/graph.tsx]: Never mind, did it myself
